import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next Hero",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <ul className=" flex justify-evenly bg-emerald-200 py-4">
            <li>About</li>
            <li>Portfolio</li>
            <li>Gallery</li>
            <li>Contact</li>
          </ul>
        </nav>
        {children}
        <footer className=" bg-emerald-200 text-center">
          <h6>All Rights resurved by Next Hero</h6>
        </footer>
      </body>
    </html>
  );
}
